version: "3.0"

services:
  db:
    container_name: mysql-server
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'local'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - common
    restart: unless-stopped

  eurekaserver:
    container_name: eureka-server
    image: eurekaserver
    build:
      context: .
      dockerfile: ./eurekaserver/Dockerfile
    ports:
      - '8761:8761'
    expose:
      - '8761'
    networks:
      - common

  customermanagementservice:
    container_name: customer-management-service
    image: customermanagementservice
    build:
      context: .
      dockerfile: ./customermanagementservice/Dockerfile
    ports:
      - '9001:9001'
    expose:
      - '9001'
    networks:
      - common
    depends_on:
      - db
      - eurekaserver

  timetablingservice:
    container_name: timetabling-service
    image: timetablingservice
    build:
      context: .
      dockerfile: ./timetablingservice/Dockerfile
    ports:
      - '9002:9002'
    expose:
      - '9002'
    networks:
      - common
    depends_on:
      - db
      - eurekaserver

  gateway:
    container_name: gateway
    image: gateway
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - '9000:9000'
    expose:
      - '9000'
    networks:
      - common
    depends_on:
      - customermanagementservice
      - timetablingservice

  interface:
    container_name: interface
    image: interface
    build:
      context: .
      dockerfile: ./interface/Dockerfile
    ports:
      - '9100:9100'
    expose:
      - '9100'
    networks:
      - common
    depends_on:
      - gateway

networks:
  common:
    driver: bridge