server:
  port: 9000

spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: ResourceManagement
          uri: lb://resourcemanagement
          predicates:
            - Path=/resource-management-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - StripPrefix=1
        - id: CustomerManagement
          uri: lb://customermanagement
          predicates:
            - Path=/customer-management-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - StripPrefix=1
        - id: Timetabling
          uri: lb://timetabling
          predicates:
            - Path=/timetabling-service/**
            - Method=GET,POST,PUT,DELETE
          filters:
             - StripPrefix=1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true