api:
  version: 0.0.1

server:
  port: 9002
  servlet:
    context-path: /

spring:
  application:
    name: Timetabling
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:mysql://mysql-server/timetabling
    username: root
    password: local

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
